name: Build and Deploy
on: [push]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false

            - name: Configure Node 🔌
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install and Build 🔧
              run: |
                  yarn
                  yarn build:prod

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: dist/portfolio
                  CLEAN: true
